# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
