# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='number',
        ),
        migrations.AddField(
            model_name='arena',
            name='name',
            field=models.CharField(default='Training Camp', max_length=3),
        ),
    ]
