# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20170413_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='arena',
            name='name',
            field=models.CharField(default='Training Camp', max_length=30),
        ),
    ]
